import type { TableColumn } from '@/types/table'

export const fundAllHeader: TableColumn[] = [
  // {id: 0, key: 'id', title: 'ID'},
  { id: 1, key: 'code', title: '基金代码' },
  //  {id: 2, key: 'pin_yin', title: '拼音缩写'},
  { id: 3, key: 'name', title: '基金简称' },
  { id: 4, key: 'fund_type', title: '基金类型' },
  //  {id: 5, key: 'pin_yin_full', title: '拼音全称'},
  { id: 6, key: 'update_time', title: '更新时间' },
  { id: 7, key: 'established_time', title: '成立时间' },
  { id: 8, key: 'latest_scale', title: '最新规模' },
  { id: 9, key: 'fund_company', title: '基金公司' },
  //  {id: 10, key: 'fund_manager', title: '基金经理'},
  //  {id: 11, key: 'proxy_bank', title: '托管银行'},
  //  {id: 12, key: 'rating_institution', title: '评级机构'},
  //  {id: 13, key: 'fund_rating', title: '基金评级'},
  // {id: 14, key: 'policy', title: '投资策略'},
  // {id: 15, key: 'goal', title: '投资目标'},
  // {id: 16, key: 'base_compare', title: '业绩比较基准'},

]

export const fundRankHeader: TableColumn[] = [
  //  {id: 0, key: 'id', title: 'ID'},
  { id: 1, key: 'code', title: '基金代码' },
  { id: 2, key: 'name', title: '基金简称' },
  { id: 3, key: 'fund_type', title: '基金类型' },
  //  {id: 4, key: 'update_time', title: '更新时间'},
  // {id: 5, key: 'established_time', title: '成立时间'},
  //  {id: 6, key: 'latest_scale', title: '最新规模'},
  //  {id: 7, key: 'fund_company', title: '基金公司'},
  //  {id: 8, key: 'follow', title: '是否关注'},
  //  {id: 9, key: 'is_purchase', title: '是否可购买'},
  //  {id: 10, key: 'currency', title: '币种'},
  //  {id: 11, key: 'category', title: '排名分类'},
  //  {id: 12, key: 'create_time', title: '创建时间'},
  //  {id: 13, key: 'update_time', title: '更新时间'},
  //  {id: 14, key: 'unit_net_value', title: '单位净值'},
  { id: 15, key: 'date', title: '日期' },
  { id: 16, key: 'day_growth_rate', title: '日增长率' },
  { id: 17, key: 'this_year_growth_rate', title: '今年以来收益(%)' },
   {id: 18, key: 'month_growth_rate', title: '近1月'},
  { id: 19, key: 'quarter_growth_rate', title: '近3月' },
  { id: 20, key: 'half_year_growth_rate', title: '近6月' },
  { id: 21, key: 'year_growth_rate', title: '近1年' },
  // { id: 22, key: 'two_year_growth_rate', title: '近2年' },
  { id: 23, key: 'three_year_growth_rate', title: '近3年' },
  //  {id: 24, key: 'this_year_growth_rate', title: '今年来'},
  { id: 25, key: 'total_growth_rate', title: '成立来' },
  { id: 26, key: 'biao_zhun_you_hui_fei_lv', title: '手续费' },

  //  {id: 27, key: 'min_purchase_amount', title: '起购金额'},
  { id: 28, key: 'track_index', title: '跟踪指数' },
  //  {id: 29, key: 'track_type', title: '跟踪方式'},
  {id: 30, key: 'established_time', title: '成立时间'},
]
