/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTable: typeof import('./components/table/AppTable.vue')['default']
    AppTopBar: typeof import('./components/appTopBar/AppTopBar.vue')['default']
    AppTopMenu: typeof import('./components/appTopBar/AppTopMenu.vue')['default']
    AppTopMenuItem: typeof import('./components/appTopBar/AppTopMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBody: typeof import('./components/table/TableBody.vue')['default']
    TableContent: typeof import('./components/table/TableBody.vue')['default']
    TableHead: typeof import('./components/table/TableHead.vue')['default']
    TableRow: typeof import('./components/table/TableRow.vue')['default']
  }
}
