/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTopBar: typeof import('./components/appTopBar/AppTopBar.vue')['default']
    AppTopMenu: typeof import('./components/appTopBar/AppTopMenu.vue')['default']
    AppTopMenuItem: typeof import('./components/appTopBar/AppTopMenuItem.vue')['default']
    FundRow: typeof import('./components/fund/FundRow.vue')['default']
    FundSearchBar: typeof import('./components/fund/FundSearchBar.vue')['default']
    FundTable: typeof import('./components/fund/FundTable.vue')['default']
    Monitor: typeof import('./components/task/TaskMonitor.vue')['default']
    MoreInfo: typeof import('./components/moreInfo/MoreInfo.vue')['default']
    NameCell: typeof import('./components/task/NameCell.vue')['default']
    NoticeConfigList: typeof import('./components/task/NoticeConfigList.vue')['default']
    NoticeInput: typeof import('./components/task/NoticeInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockRow: typeof import('./components/stock/StockRow.vue')['default']
    StockSelect: typeof import('./components/task/StockSelect.vue')['default']
    StockTable: typeof import('./components/stock/StockTable.vue')['default']
    StockTableHeader: typeof import('./components/stock/StockTableHeader.vue')['default']
    TableActions: typeof import('./components/task/TableActions.vue')['default']
    TaskDialog: typeof import('./components/task/TaskDialog.vue')['default']
    TaskMonitor: typeof import('./components/task/TaskMonitor.vue')['default']
    TaskTable: typeof import('./components/task/TaskTable.vue')['default']
    TaskTableBar: typeof import('./components/task/TaskTableBar.vue')['default']
    TaskTableHistoryRow: typeof import('./components/task/TaskTableHistoryRow.vue')['default']
  }
}
