/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/favorate/fund': RouteRecordInfo<'/favorate/fund', '/favorate/fund', Record<never, never>, Record<never, never>>,
    '/favorate/stock': RouteRecordInfo<'/favorate/stock', '/favorate/stock', Record<never, never>, Record<never, never>>,
    '/fund/foreign': RouteRecordInfo<'/fund/foreign', '/fund/foreign', Record<never, never>, Record<never, never>>,
    '/fund/internal': RouteRecordInfo<'/fund/internal', '/fund/internal', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/note': RouteRecordInfo<'/note', '/note', Record<never, never>, Record<never, never>>,
    '/stock': RouteRecordInfo<'/stock', '/stock', Record<never, never>, Record<never, never>>,
    '/task': RouteRecordInfo<'/task', '/task', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/favorate/fund.vue': {
      routes: '/favorate/fund'
      views: never
    }
    'src/pages/favorate/stock.vue': {
      routes: '/favorate/stock'
      views: never
    }
    'src/pages/fund/foreign.vue': {
      routes: '/fund/foreign'
      views: never
    }
    'src/pages/fund/internal.vue': {
      routes: '/fund/internal'
      views: never
    }
    'src/pages/history.vue': {
      routes: '/history'
      views: never
    }
    'src/pages/note.vue': {
      routes: '/note'
      views: never
    }
    'src/pages/stock.vue': {
      routes: '/stock'
      views: never
    }
    'src/pages/task.vue': {
      routes: '/task'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
